name: Build PKI

on: [push, pull_request]

jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/init.yml
    secrets: inherit

  build:
    name: Building PKI
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build pki-runner image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ needs.init.outputs.base-image }}
            COPR_REPO=${{ needs.init.outputs.repo }}
          tags: pki-runner
          target: pki-runner
          outputs: type=docker,dest=pki-runner.tar

      - name: Store pki-runner image
        uses: actions/cache@v3
        with:
          key: pki-runner-${{ github.sha }}
          path: pki-runner.tar

      - name: Build pki-acme image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ needs.init.outputs.base-image }}
            COPR_REPO=${{ needs.init.outputs.repo }}
          tags: pki-acme
          target: pki-acme
          outputs: type=docker,dest=pki-acme.tar

      - name: Store pki-acme image
        uses: actions/cache@v3
        with:
          key: pki-acme-${{ github.sha }}
          path: pki-acme.tar
