name: PKI NSS CLI with AES

on: workflow_call

env:
  DB_IMAGE: ${{ vars.DB_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  # https://github.com/dogtagpki/pki/wiki/PKI-NSS-CLI
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Set up runner container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              pki

      - name: Create AES key
        run: |
          docker exec pki pki nss-key-create --key-type AES test | tee output

          # verify with tkstool
          docker exec pki tkstool -L -d /root/.dogtag/nssdb | tee output
          echo "test" > expected
          sed -n 's/^\s*<.\+>\s\+\(\S\+\)\s*$/\1/p' output > actual
          diff expected actual

      - name: Verify key type
        run: |
          echo aes > expected

          docker exec pki pki nss-key-find | tee output

          sed -n 's/\s*Type:\s*\(\S\+\)\s*$/\L\1/p' output > actual
          diff expected actual
