name: rpminspect

on: workflow_call

env:
  DB_IMAGE: ${{ vars.DB_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Set up PKI container
        run: |
          tests/bin/runner-init.sh \
              --hostname=pki.example.com \
              pki

      - name: Install rpminspect
        run: |
          docker exec pki dnf install -y rpminspect-data-fedora

      - name: Copy SRPM and RPM packages
        run: |
          docker create --name=pki-dist pki-dist

          mkdir /tmp/build
          docker cp pki-dist:/root/SRPMS/. /tmp/build/SRPMS
          docker cp pki-dist:/root/RPMS/. /tmp/build/RPMS
          ls -lR /tmp/build

          docker exec pki mkdir -p build
          docker cp /tmp/build/. pki:build/
          docker exec pki ls -lR build

          docker rm -f pki-dist

      - name: Run rpminspect on SRPM and RPMs
        run: |
          docker exec pki cp /usr/share/pki/tests/pki-rpminspect.yaml /usr/share/rpminspect/profiles/fedora/pki-rpminspect.yaml
          docker exec pki /usr/share/pki/tests/bin/rpminspect.sh
